# Site
name: 'HỌC.place'
description: 'HỌC place - Nơi Bạn Học Mọi Thứ.'
logo: 'assets/images/hoc.png'
favicon: 'assets/images/hoc.png'
baseurl: ''
# disqus: 'demowebsite'
email: 'hocbaicungcon@gmail.com'
# mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins: 
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-glossary_tooltip
  
authors:
    sloth:
      name:           Sloth
      site:           https://amthanhnhapkhau.com.vn
      avatar:         assets/images/sloth.webp
      bio:            "Hi, I am Sloth, the author of HỌC.place. I hope you like it!"
      email:          hocbaicungcon@gmail.com
      youtube:        https://youtube.com/dummyfresher
      # twitter:        https://twitter.com/wowthemesnet

    jane:
      name:           Jane
      site:           https://o2.edu.vn
      avatar:         assets/images/avatar2.jpg
      bio:            "Blogger, fashionista, love to explore new ideas and write on my morning coffee!"
      email:          admin@o2.edu.vn
      youtube:        https://youtube.com/minismart
      # twitter:        https://twitter.com/wowthemesnet
 
# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: sloth
      avatar: /assets/images/avatar1.jpg
      
  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page
      
# Syntax
markdown: kramdown
highlighter: rouge

# # Build settings
# markdown: kramdown

# Paginate
paginate: 10
  

# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]